SELECT * FROM tab;
SELECT * FROM pinoinsa_member WHERE TO_CHAR(JOIN_DAY, 'YYYY-MM-DD') = '2022-10-10' ;
SELECT * FROM insa_com ORDER BY GUBUN ;
SELECT * FROM pinoinsa_member ORDER BY sabun;
SELECT * FROM INSA_INPUT_INFO ;
DELETE FROM PINOINSA_MEMBER WHERE NAME = '홍길순';
COMMIT;
DROP TABLE PINOINSA_MEMBER ;
DROP SEQUENCE SABUN_SEQ;


CREATE TABLE PINOINSA_MEMBER ( 
	SABUN NUMBER NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	ENG_NAME VARCHAR2(100),
	ID VARCHAR2(100) NOT NULL,
	PWD VARCHAR2(100) NOT NULL,
	HP VARCHAR2(100) NOT NULL,
	PHONE VARCHAR2(100),
	REG_NO VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	JOB_TYPE VARCHAR2(100),
	YEARS NUMBER,
	SEX VARCHAR2(100),
	ZIP NUMBER,
	ADDR1 VARCHAR2(100),
	ADDR2 VARCHAR2(100),
	POS_GBN_CODE VARCHAR2(100),
	DEPT_CODE VARCHAR2(100),
	SALARY NUMBER,
	JOIN_GBN_CODE VARCHAR2(100),
	GART_LEVEL VARCHAR2(100),
	PUT_YN VARCHAR2(100),
	MIL_YN VARCHAR2(100),
	MIL_TYPE VARCHAR(100),
	MIL_LEVEL VARCHAR(100),
	MIL_STARTDATE DATE,
	MIL_ENDDATE DATE,
	KOSA_REG_YN VARCHAR2(100),
	KOSA_CLASS_CODE VARCHAR2(100),
	JOIN_DAY DATE NOT NULL,
	RETIRE_DAY DATE,
	CMP_REG_NO VARCHAR2(100),
	CRM_NAME VARCHAR2(100),
	CMP_REG_IMAGE VARCHAR2(100),
	SELF_INTRO VARCHAR2(100),
	PROFILE VARCHAR2(100),
	CARRIER VARCHAR2(100),
	PROFILE_IMAGE VARCHAR2(100),
	CARRIER_IMAGE VARCHAR2(100),
	CONSTRAINT PINOINSA_MEMBER_PK PRIMARY KEY (SABUN)
);

CREATE SEQUENCE SABUN_SEQ;

insert INTO pinoinsa_member
	(sabun,name,eng_name,id,pwd,hp,phone,reg_no,email,job_type,years,sex,zip,addr1,addr2,pos_gbn_code,dept_code,salary,
	join_gbn_code,carrier,put_yn,mil_yn,mil_type,mil_level,mil_startDate,mil_endDate,kosa_reg_yn,kosa_class_code,
	join_day,retire_day,cmp_reg_no,crm_name,cmp_reg_image,self_intro,profile,gart_level)
VALUES
	(sabun_seq.nextval,'테스트','test','test','asdasdasd','010-1234-5678','02-345-6789','920405-1455413','test@naver.com',
	'',30,'남자',123123,'서울시','어딘가','','',3000,'','','N','Y','육군','병장','20120508',
	'20140207','N','',sysdate,NULL,'','','','Hi','','대졸');
	    	

CREATE TABLE INSA_COM (
	GUBUN VARCHAR2(20),
	CODE VARCHAR2(20),
	NAME VARCHAR2(20),
	NOTE VARCHAR2(20),
	CONSTRAINT INSA_COM_PK PRIMARY KEY(GUBUN, CODE)
)

INSERT INTO INSA_COM (gubun, code, name, note) VALUES ('112','103','대졸','최종학력');


CREATE TABLE INSA_INPUT_INFO(
	SEQ NUMBER NOT NULL,
	WRK_POSB_DAY DATE,
	SUGST_MONEY NUMBER,
	PJT_GBN_CODE VARCHAR2(20),
	EQM_YN VARCHAR2(10),
	CURRENT_SALARY NUMBER,
	WORK_AREA VARCHAR2(100),
	SABUN NUMBER NOT NULL,    
    CONSTRAINT sabun_fk foreign key(sabun) references pinoinsa_member (sabun),
    CONSTRAINT insa_input_info_pk PRIMARY KEY (seq)
);

CREATE SEQUENCE INSA_INPUT_INFO_SEQ;
INSERT INTO INSA_INPUT_INFO VALUES (insa_input_info_seq.nextval, '20220101', '400', '101101', 'Y', '5000', '서울 가산동', 2);
